kind: pipeline
type: docker
name: ensurance-pharmacy-pipeline

clone:
  disable: false

environment:
  EMAIL_TO: pablopolis2016@gmail.com,jflores@unis.edu.gt

steps:
  - name: unit-tests
    image: maven:3.9-openjdk-23
    environment:
      MAVEN_OPTS: -Dmaven.repo.local=/tmp/.m2
    commands:
      - echo "Running unit tests and generating coverage reports..."
      - mvn -B clean test jacoco:report -f backv4/pom.xml
      - mvn -B clean test jacoco:report -f backv5/pom.xml
    volumes:
      - name: maven-cache
        path: /tmp/.m2
    when:
      branch:
        - main
        - master
        - develop
        - dev
        - qa
        - feature/*

  - name: sonarqube-ensurance-backend-analysis-dev
    image: sonarqube/sonar-scanner-cli:latest
    environment:
      SONAR_TOKEN:
        from_secret: ensurance_back_dev
      SONAR_HOST_URL: https://macbook-air-de-gp.tail5d54f7.ts.net/sonar
    commands:
      - echo "SonarQube Ensurance Backend analysis for DEV environment"
      - sonar-scanner -Dsonar.projectKey=ENSURANCE_BACK_DEV -Dsonar.projectName="Ensurance Backend DEV" -Dsonar.projectVersion=${DRONE_BUILD_NUMBER} -Dsonar.sources=backv4/src/main -Dsonar.tests=backv4/src/test -Dsonar.java.binaries=backv4/target/classes -Dsonar.coverage.jacoco.xmlReportPaths=backv4/target/site/jacoco/jacoco.xml -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300
    when:
      branch:
        - develop
        - dev
        - feature/*

  - name: sonarqube-ensurance-frontend-analysis-dev
    image: sonarqube/sonar-scanner-cli:latest
    environment:
      SONAR_TOKEN:
        from_secret: ensurance_front_dev
      SONAR_HOST_URL: https://macbook-air-de-gp.tail5d54f7.ts.net/sonar
    commands:
      - echo "SonarQube Ensurance Frontend analysis for DEV environment"
      - cd ensurance && npm ci && npm run test:coverage || true && cd ..
      - sonar-scanner -Dsonar.projectKey=ENSURANCE_FRONT_DEV -Dsonar.projectName="Ensurance Frontend DEV" -Dsonar.projectVersion=${DRONE_BUILD_NUMBER} -Dsonar.sources=ensurance/src -Dsonar.tests=ensurance/tests -Dsonar.javascript.lcov.reportPaths=ensurance/coverage/lcov.info -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300
    when:
      branch:
        - develop
        - dev
        - feature/*

  - name: sonarqube-pharmacy-backend-analysis-dev
    image: sonarqube/sonar-scanner-cli:latest
    environment:
      SONAR_TOKEN:
        from_secret: pharmacy_back_dev
      SONAR_HOST_URL: https://macbook-air-de-gp.tail5d54f7.ts.net/sonar
    commands:
      - echo "SonarQube Pharmacy Backend analysis for DEV environment"
      - sonar-scanner -Dsonar.projectKey=PHARMACY_BACK_DEV -Dsonar.projectName="Pharmacy Backend DEV" -Dsonar.projectVersion=${DRONE_BUILD_NUMBER} -Dsonar.sources=backv5/src/main -Dsonar.tests=backv5/src/test -Dsonar.java.binaries=backv5/target/classes -Dsonar.coverage.jacoco.xmlReportPaths=backv5/target/site/jacoco/jacoco.xml -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300
    when:
      branch:
        - develop
        - dev
        - feature/*

  - name: sonarqube-pharmacy-frontend-analysis-dev
    image: sonarqube/sonar-scanner-cli:latest
    environment:
      SONAR_TOKEN:
        from_secret: pharmacy_front_dev
      SONAR_HOST_URL: https://macbook-air-de-gp.tail5d54f7.ts.net/sonar
    commands:
      - echo "SonarQube Pharmacy Frontend analysis for DEV environment"
      - cd pharmacy && npm ci && npm run test:unit:coverage || true && cd ..
      - sonar-scanner -Dsonar.projectKey=PHARMACY_FRONT_DEV -Dsonar.projectName="Pharmacy Frontend DEV" -Dsonar.projectVersion=${DRONE_BUILD_NUMBER} -Dsonar.sources=pharmacy/src -Dsonar.tests=pharmacy/tests -Dsonar.javascript.lcov.reportPaths=pharmacy/coverage/lcov.info -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300
    when:
      branch:
        - develop
        - dev
        - feature/*

  - name: sonarqube-ensurance-backend-analysis-qa
    image: sonarqube/sonar-scanner-cli:latest
    environment:
      SONAR_TOKEN:
        from_secret: ensurance_back_qa
      SONAR_HOST_URL: https://macbook-air-de-gp.tail5d54f7.ts.net/sonar
    commands:
      - echo "SonarQube Ensurance Backend analysis for QA environment"
      - sonar-scanner -Dsonar.projectKey=ENSURANCE_BACK_QA -Dsonar.projectName="Ensurance Backend QA" -Dsonar.projectVersion=${DRONE_BUILD_NUMBER} -Dsonar.sources=backv4/src/main -Dsonar.tests=backv4/src/test -Dsonar.java.binaries=backv4/target/classes -Dsonar.coverage.jacoco.xmlReportPaths=backv4/target/site/jacoco/jacoco.xml -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300
    when:
      branch:
        - qa

  - name: sonarqube-ensurance-frontend-analysis-qa
    image: sonarqube/sonar-scanner-cli:latest
    environment:
      SONAR_TOKEN:
        from_secret: ensurance_front_qa
      SONAR_HOST_URL: https://macbook-air-de-gp.tail5d54f7.ts.net/sonar
    commands:
      - echo "SonarQube Ensurance Frontend analysis for QA environment"
      - cd ensurance && npm ci && npm run test:coverage || true && cd ..
      - sonar-scanner -Dsonar.projectKey=ENSURANCE_FRONT_QA -Dsonar.projectName="Ensurance Frontend QA" -Dsonar.projectVersion=${DRONE_BUILD_NUMBER} -Dsonar.sources=ensurance/src -Dsonar.tests=ensurance/tests -Dsonar.javascript.lcov.reportPaths=ensurance/coverage/lcov.info -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300
    when:
      branch:
        - qa

  - name: sonarqube-pharmacy-backend-analysis-qa
    image: sonarqube/sonar-scanner-cli:latest
    environment:
      SONAR_TOKEN:
        from_secret: pharmacy_back_qa
      SONAR_HOST_URL: https://macbook-air-de-gp.tail5d54f7.ts.net/sonar
    commands:
      - echo "SonarQube Pharmacy Backend analysis for QA environment"
      - sonar-scanner -Dsonar.projectKey=PHARMACY_BACK_QA -Dsonar.projectName="Pharmacy Backend QA" -Dsonar.projectVersion=${DRONE_BUILD_NUMBER} -Dsonar.sources=backv5/src/main -Dsonar.tests=backv5/src/test -Dsonar.java.binaries=backv5/target/classes -Dsonar.coverage.jacoco.xmlReportPaths=backv5/target/site/jacoco/jacoco.xml -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300
    when:
      branch:
        - qa

  - name: sonarqube-pharmacy-frontend-analysis-qa
    image: sonarqube/sonar-scanner-cli:latest
    environment:
      SONAR_TOKEN:
        from_secret: pharmacy_front_qa
      SONAR_HOST_URL: https://macbook-air-de-gp.tail5d54f7.ts.net/sonar
    commands:
      - echo "SonarQube Pharmacy Frontend analysis for QA environment"
      - cd pharmacy && npm ci && npm run test:unit:coverage || true && cd ..
      - sonar-scanner -Dsonar.projectKey=PHARMACY_FRONT_QA -Dsonar.projectName="Pharmacy Frontend QA" -Dsonar.projectVersion=${DRONE_BUILD_NUMBER} -Dsonar.sources=pharmacy/src -Dsonar.tests=pharmacy/tests -Dsonar.javascript.lcov.reportPaths=pharmacy/coverage/lcov.info -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300
    when:
      branch:
        - qa

  - name: sonarqube-ensurance-backend-analysis-main
    image: sonarqube/sonar-scanner-cli:latest
    environment:
      SONAR_TOKEN:
        from_secret: ensurance_back_main
      SONAR_HOST_URL: https://macbook-air-de-gp.tail5d54f7.ts.net/sonar
    commands:
      - echo "SonarQube Ensurance Backend analysis for MAIN environment"
      - sonar-scanner -Dsonar.projectKey=ENSURANCE_BACK_MAIN -Dsonar.projectName="Ensurance Backend MAIN" -Dsonar.projectVersion=${DRONE_BUILD_NUMBER} -Dsonar.sources=backv4/src/main -Dsonar.tests=backv4/src/test -Dsonar.java.binaries=backv4/target/classes -Dsonar.coverage.jacoco.xmlReportPaths=backv4/target/site/jacoco/jacoco.xml -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300
    when:
      branch:
        - main
        - master

  - name: sonarqube-ensurance-frontend-analysis-main
    image: sonarqube/sonar-scanner-cli:latest
    environment:
      SONAR_TOKEN:
        from_secret: ensurance_front_main
      SONAR_HOST_URL: https://macbook-air-de-gp.tail5d54f7.ts.net/sonar
    commands:
      - echo "SonarQube Ensurance Frontend analysis for MAIN environment"
      - cd ensurance && npm ci && npm run test:coverage || true && cd ..
      - sonar-scanner -Dsonar.projectKey=ENSURANCE_FRONT_MAIN -Dsonar.projectName="Ensurance Frontend MAIN" -Dsonar.projectVersion=${DRONE_BUILD_NUMBER} -Dsonar.sources=ensurance/src -Dsonar.tests=ensurance/tests -Dsonar.javascript.lcov.reportPaths=ensurance/coverage/lcov.info -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300
    when:
      branch:
        - main
        - master

  - name: sonarqube-pharmacy-backend-analysis-main
    image: sonarqube/sonar-scanner-cli:latest
    environment:
      SONAR_TOKEN:
        from_secret: pharmacy_back_main
      SONAR_HOST_URL: https://macbook-air-de-gp.tail5d54f7.ts.net/sonar
    commands:
      - echo "SonarQube Pharmacy Backend analysis for MAIN environment"
      - sonar-scanner -Dsonar.projectKey=PHARMACY_BACK_MAIN -Dsonar.projectName="Pharmacy Backend MAIN" -Dsonar.projectVersion=${DRONE_BUILD_NUMBER} -Dsonar.sources=backv5/src/main -Dsonar.tests=backv5/src/test -Dsonar.java.binaries=backv5/target/classes -Dsonar.coverage.jacoco.xmlReportPaths=backv5/target/site/jacoco/jacoco.xml -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300
    when:
      branch:
        - main
        - master

  - name: sonarqube-pharmacy-frontend-analysis-main
    image: sonarqube/sonar-scanner-cli:latest
    environment:
      SONAR_TOKEN:
        from_secret: pharmacy_front_main
      SONAR_HOST_URL: https://macbook-air-de-gp.tail5d54f7.ts.net/sonar
    commands:
      - echo "SonarQube Pharmacy Frontend analysis for MAIN environment"
      - cd pharmacy && npm ci && npm run test:unit:coverage || true && cd ..
      - sonar-scanner -Dsonar.projectKey=PHARMACY_FRONT_MAIN -Dsonar.projectName="Pharmacy Frontend MAIN" -Dsonar.projectVersion=${DRONE_BUILD_NUMBER} -Dsonar.sources=pharmacy/src -Dsonar.tests=pharmacy/tests -Dsonar.javascript.lcov.reportPaths=pharmacy/coverage/lcov.info -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300
    when:
      branch:
        - main
        - master

  - name: deploy-dev
    image: docker/compose:latest
    environment:
      ENVIRONMENT: dev
    commands:
      - echo "Deploy DEV Environment (puertos 3000-3003)"
      - docker-compose -f docker-compose.dev.yml down || true
      - ENVIRONMENT=dev docker-compose -f docker-compose.dev.yml up -d --build
      - sleep 30
      - docker-compose -f docker-compose.dev.yml ps
      - echo "DEV desplegado en:"
      - 'echo "   - Ensurance Frontend: http://localhost:3000"'
      - 'echo "   - Pharmacy Frontend: http://localhost:3001"'
      - 'echo "   - Ensurance Backend: http://localhost:3002/api"'
      - 'echo "   - Pharmacy Backend: http://localhost:3003/api2"'
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    when:
      branch:
        - develop
        - dev
        - feature/*

  - name: deploy-qa
    image: docker/compose:latest
    environment:
      ENVIRONMENT: qa
    commands:
      - echo "Deploy QA Environment (puertos 4000-4003)"
      - docker-compose -f docker-compose.qa.yml down || true
      - ENVIRONMENT=qa docker-compose -f docker-compose.qa.yml up -d --build
      - sleep 30
      - docker-compose -f docker-compose.qa.yml ps
      - echo "QA desplegado en:"
      - 'echo "   - Ensurance Frontend: http://localhost:4000"'
      - 'echo "   - Pharmacy Frontend: http://localhost:4001"'
      - 'echo "   - Ensurance Backend: http://localhost:4002/api"'
      - 'echo "   - Pharmacy Backend: http://localhost:4003/api2"'
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    when:
      branch:
        - qa

  - name: deploy-main
    image: docker/compose:latest
    environment:
      ENVIRONMENT: main
    commands:
      - echo "Deploy MAIN Environment (puertos 5000-5003)"
      - docker-compose -f docker-compose.main.yml down || true
      - ENVIRONMENT=main docker-compose -f docker-compose.main.yml up -d --build
      - sleep 30
      - docker-compose -f docker-compose.main.yml ps
      - echo "MAIN desplegado en:"
      - 'echo "   - Ensurance Frontend: http://localhost:5000"'
      - 'echo "   - Pharmacy Frontend: http://localhost:5001"'
      - 'echo "   - Ensurance Backend: http://localhost:5002/api"'
      - 'echo "   - Pharmacy Backend: http://localhost:5003/api2"'
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    when:
      branch:
        - main
        - master

  - name: verify-deployment
    image: curlimages/curl:latest
    commands:
      - export ENVIRONMENT=$(cat .environment)
      - echo "Verificando deployment en ambiente: $ENVIRONMENT"
      - sh -c "if [ \"$ENVIRONMENT\" = \"dev\" ]; then curl -f http://localhost:3000 || echo \"Frontend DEV no responde\"; curl -f http://localhost:3002/api || echo \"Backend DEV no responde\"; elif [ \"$ENVIRONMENT\" = \"qa\" ]; then curl -f http://localhost:4000 || echo \"Frontend QA no responde\"; curl -f http://localhost:4002/api || echo \"Backend QA no responde\"; elif [ \"$ENVIRONMENT\" = \"main\" ]; then curl -f http://localhost:5000 || echo \"Frontend MAIN no responde\"; curl -f http://localhost:5002/api || echo \"Backend MAIN no responde\"; fi"
    depends_on:
      - deploy-dev
      - deploy-qa
      - deploy-main

  - name: notify-success
    image: alpine
    commands:
      - export ENVIRONMENT=$(cat .environment)
      - echo "Pipeline completado exitosamente para ambiente: $ENVIRONMENT"
      - echo "Quality Gate: APROBADO"
      - echo "Tests: PASADOS"
      - echo "Deploy: EXITOSO"
      - echo "Notificaci贸n enviada a: ${EMAIL_TO}"
    when:
      status:
        - success

  - name: notify-failure
    image: alpine
    commands:
      - export ENVIRONMENT=$(cat .environment)
      - echo "Pipeline fall贸 para ambiente: $ENVIRONMENT"
      - echo "Revisar logs en: ${DRONE_BUILD_LINK}"
      - echo "Notificaci贸n de fallo enviada a: ${EMAIL_TO}"
    when:
      status:
        - failure

volumes:
  - name: maven-cache
    host:
      path: /tmp/drone-maven-cache
  - name: node-cache
    host:
      path: /tmp/drone-node-cache
  - name: docker-sock
    host:
      path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: notifications

depends_on:
  - ensurance-pharmacy-pipeline

steps:
  - name: email-notification
    image: drillster/drone-email
    settings:
      host: smtp.gmail.com
      port: 587
      username:
        from_secret: email_username
      password:
        from_secret: email_password
      from: drone@ensurance-pharmacy.com
      to:
        - pablopolis2016@gmail.com
        - jflores@unis.edu.gt
      subject: "{{#success build.status}}Deploy exitoso: {{repo.name}} #{{build.number}} [{{build.branch}}]{{else}}Pipeline fallido: {{repo.name}} #{{build.number}} [{{build.branch}}]{{/success}}"
      body: "{{#success build.status}}Deploy completado exitosamente en rama {{build.branch}}.\n\nQuality Gate: APROBADO\nTests: PASADOS\nDeploy: EXITOSO\n\nDetalles: {{build.link}}\n\nServicios disponibles:\n{{#equal build.branch \"develop\"}}- Ensurance Frontend: http://localhost:3000\n- Pharmacy Frontend: http://localhost:3001\n- Ensurance Backend: http://localhost:3002/api\n- Pharmacy Backend: http://localhost:3003/api2\n{{/equal}}{{#equal build.branch \"qa\"}}- Ensurance Frontend: http://localhost:4000\n- Pharmacy Frontend: http://localhost:4001\n- Ensurance Backend: http://localhost:4002/api\n- Pharmacy Backend: http://localhost:4003/api2\n{{/equal}}{{#equal build.branch \"main\"}}- Ensurance Frontend: http://localhost:5000\n- Pharmacy Frontend: http://localhost:5001\n- Ensurance Backend: http://localhost:5002/api\n- Pharmacy Backend: http://localhost:5003/api2\n{{/equal}}{{else}}Pipeline fall贸 en rama {{build.branch}}.\n\nDetalle: {{build.link}}\n\nPara diagnosticar:\n1. Revisar logs en Drone UI\n2. Verificar Quality Gate en SonarQube\n3. Revisar estado de contenedores{{/success}}"

trigger:
  status:
    - success
    - failure
