services:
  ensurance-db1:
    build:
      context: .
      dockerfile: Dockerfile.ensurance.db
    ports:
      - "5170:1521"
      - "5171:5500"
    volumes:
      - db-data1:/app/oracle/oradata
  ensurance-db2:
    build:
      context: .
      dockerfile: Dockerfile.ensurance.db
    ports:
      - "5172:1521"
      - "5173:5500"
    volumes:
      - db-data2:/app/oracle/oradata
  ensurance-db3:
    build:
      context: .
      dockerfile: Dockerfile.ensurance.db
    ports:
      - "5174:1521"
      - "5175:5500"
    volumes:
      - db-data3:/app/oracle/oradata
  ensurance-backend1:
    build:
      context: .
      dockerfile: Dockerfile.ensurance.backend
    ports:
      - "5176:8080"
    depends_on:
      - ensurance-db1
  ensurance-backend2:
    build:
      context: .
      dockerfile: Dockerfile.ensurance.backend
    ports:
      - "5177:8080"
    depends_on:
      - ensurance-db2
  ensurance-backend3:
    build:
      context: .
      dockerfile: Dockerfile.ensurance.backend
    ports:
      - "5178:8080"
    depends_on:
      - ensurance-db3
  ensurance-frontend1:
    build:
      context: .
      dockerfile: Dockerfile.ensurance.frontend
    ports:
      - "5179:5173"
    depends_on:
      - ensurance-backend1
  ensurance-frontend2:
    build:
      context: .
      dockerfile: Dockerfile.ensurance.frontend
    ports:
      - "5180:5173"
    depends_on:
      - ensurance-backend2
  ensurance-frontend3:
    build:
      context: .
      dockerfile: Dockerfile.ensurance.frontend
    ports:
      - "5181:5173"
    depends_on:
      - ensurance-backend3
volumes:
  db-data1:
  db-data2:
  db-data3:
