version: "3.9"

services:
  ensurance-backend:
    build:
      context: .
      dockerfile: Dockerfile.ensurance.backend  # backv4 (HTTP default 8080)
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "8080"
    ports:
      - "${ENS_BACKEND_HOST_PORT:-8081}:8080"   # host -> container:8080
    restart: unless-stopped

  ensurance-frontend:
    build:
      context: .
      dockerfile: Dockerfile.ensurance.frontend # Vite dev server (EXPOSE 5173)
    ports:
      - "5175:5173"                             # http://localhost:5175
    environment:
      # URLs base para que el frontend apunte al backend expuesto
      VITE_ENSURANCE_API_URL: "${VITE_ENSURANCE_API_URL:-http://localhost:${ENS_BACKEND_HOST_PORT:-8081}/api}"
      VITE_PHARMACY_API_URL:  "${VITE_PHARMACY_API_URL:-http://localhost:${PHARM_BACKEND_HOST_PORT:-8082}/api2}"
    depends_on:
      - ensurance-backend
    restart: unless-stopped

