FROM eclipse-temurin:24-jdk-alpine

WORKDIR /app

# Instala Maven en Alpine
RUN apk add --no-cache maven

# Copia tu backend (ajusta la ruta si cambia)
COPY backv4/ .

# Compila (puedes añadir -DskipTests si quieres)
RUN mvn -B clean install

EXPOSE 8080

# Ejecuta con el exec-maven-plugin (no uses bash en Alpine)
CMD ["sh","-lc","mvn -q exec:java -Dexec.mainClass=com.sources.app.App"]
