FROM container-registry.oracle.com/java/jdk:24-oraclelinux9

WORKDIR /app

COPY backv5 /app

RUN dnf install maven -y

RUN mvn clean install -DskipTests

EXPOSE 8081

CMD ["/bin/sh", "-c", "mvn clean compile exec:java -Dexec.mainClass='com.sources.app.App'"]