version: "3.9"

services:
  ensurance-backend:
    build:
      context: .
      dockerfile: Dockerfile.ensurance.backend  # backv4 (HTTP default 8080)
    ports:
      - "5172:8080"                             # http://localhost:5172 -> container:8080
    restart: unless-stopped

  ensurance-frontend:
    build:
      context: .
      dockerfile: Dockerfile.ensurance.frontend # Vite dev server (EXPOSE 5173)
    ports:
      - "5175:5173"                             # http://localhost:5175
    environment:
      VITE_API_URL: "http://localhost:5172"
      REACT_APP_API_URL: "http://localhost:5172"
      VUE_APP_API_URL: "http://localhost:5172"
      API_BASE_URL: "http://localhost:5172"
    depends_on:
      - ensurance-backend
    restart: unless-stopped

