services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 60000:9443
      - 60001:8000

volumes:
  portainer_data:
    name: portainer_data

networks:
  default:
    name: portainer_network