#!/bin/bash

# Script para recrear completamente CheckMK desde cero (sin confirmación)

echo "═══════════════════════════════════════════════════════════════════"
echo "  Recreando CheckMK Completamente"
echo "═══════════════════════════════════════════════════════════════════"

echo ""
echo "[1/6] Deteniendo CheckMK..."
docker compose -f docker-compose.full.yml stop checkmk 2>&1
sleep 3

echo ""
echo "[2/6] Eliminando contenedor..."
docker compose -f docker-compose.full.yml rm -f checkmk 2>&1

echo ""
echo "[3/6] Eliminando volumen corrupto..."
docker volume rm ensurance-checkmk-sites-full 2>&1 || echo "  (Continuando...)"

echo ""
echo "[4/6] Recreando CheckMK desde cero..."
docker compose -f docker-compose.full.yml up -d checkmk 2>&1

echo ""
echo "[5/6] Esperando que CheckMK inicie (90 segundos)..."
for i in {90..1}; do
    echo -ne "  Esperando... $i segundos restantes\r"
    sleep 1
done
echo -e "\n"

echo ""
echo "[6/6] Verificando estado..."
docker ps | grep checkmk

echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "  ✅ CheckMK Recreado y Listo"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "ACCESO:"
echo "  http://localhost:5152/ensurance/check_mk/"
echo "  Usuario: cmkadmin"
echo "  Password: admin123"
echo ""
echo "AHORA SIGUE ESTOS PASOS (manualmente desde la Web UI):"
echo ""
echo "1. Accede a CheckMK en tu navegador"
echo "2. Ve a 'Setup > Hosts'"
echo "3. Haz clic en 'Add host'"
echo "4. Agrega CADA host con estos datos:"
echo ""
echo "   Host 1:"
echo "   ├─ Hostname: prometheus"
echo "   ├─ Alias: Prometheus Server"  
echo "   ├─ IPv4 Address: ensurance-prometheus-full"
echo "   └─ Monitoring agents: No agent"
echo ""
echo "   Host 2:"
echo "   ├─ Hostname: grafana"
echo "   ├─ Alias: Grafana Dashboard"
echo "   ├─ IPv4 Address: ensurance-grafana-full"
echo "   └─ Monitoring agents: No agent"
echo ""
echo "   Host 3:"
echo "   ├─ Hostname: alertmanager"
echo "   ├─ Alias: Alert Manager"
echo "   ├─ IPv4 Address: ensurance-alertmanager-full"
echo "   └─ Monitoring agents: No agent"
echo ""
echo "   Host 4:"
echo "   ├─ Hostname: rabbitmq"
echo "   ├─ Alias: RabbitMQ"
echo "   ├─ IPv4 Address: ensurance-rabbitmq-full"
echo "   └─ Monitoring agents: No agent"
echo ""
echo "   Host 5:"
echo "   ├─ Hostname: netdata"
echo "   ├─ Alias: Netdata Monitoring"
echo "   ├─ IPv4 Address: ensurance-netdata-full"
echo "   └─ Monitoring agents: No agent"
echo ""
echo "   Host 6:"
echo "   ├─ Hostname: node-exporter"
echo "   ├─ Alias: Node Exporter"
echo "   ├─ IPv4 Address: ensurance-node-exporter-full"
echo "   └─ Monitoring agents: No agent"
echo ""
echo "   Host 7:"
echo "   ├─ Hostname: pushgateway"
echo "   ├─ Alias: Pushgateway"
echo "   ├─ IPv4 Address: ensurance-pushgateway-full"
echo "   └─ Monitoring agents: No agent"
echo ""
echo "   Host 8:"
echo "   ├─ Hostname: ensurance-app"
echo "   ├─ Alias: Ensurance App"
echo "   ├─ IPv4 Address: ensurance-pharmacy-full"
echo "   └─ Monitoring agents: No agent"
echo ""
echo "5. Después de agregar TODOS los hosts:"
echo "   - Ve a 'Setup > Hosts'"
echo "   - Selecciona todos los hosts (checkbox arriba)"
echo "   - Haz clic en 'Bulk discovery'"
echo "   - Selecciona 'Full scan'"
echo "   - Haz clic en 'Start'"
echo ""
echo "6. Finalmente:"
echo "   - Haz clic en el banner amarillo 'X changes'"
echo "   - Haz clic en 'Activate affected'"
echo "   - ESPERA hasta que termine (puede tomar 1-2 minutos)"
echo ""
echo "7. Ve a 'Monitor > All Hosts' para ver tus hosts"
echo ""
