# ALERTAS DE K6 STRESS TESTING
# Monitorea performance durante tests de carga

groups:
  - name: k6_performance_alerts
    interval: 15s
    rules:
      # ALERTA 33: Alta tasa de errores en K6
      - alert: K6HighErrorRate
        expr: k6_http_req_failed > 0.05
        for: 1m
        labels:
          severity: critical
          service: k6-stress-testing
          component: load-test
        annotations:
          summary: "⚠️ Alta tasa de errores en test K6"
          description: "Tasa de errores: {{ $value | humanizePercentage }} (umbral: 5%)"
          dashboard: "http://localhost:3302/d/k6-stress-test"
          action: "Revisar aplicación bajo test, posible fallo"
      
      # ALERTA 34: Response time p95 alto
      - alert: K6HighResponseTimeP95
        expr: k6_http_req_duration{quantile="0.95"} > 1000
        for: 2m
        labels:
          severity: warning
          service: k6-stress-testing
          component: performance
        annotations:
          summary: "Response time p95 alto en test K6"
          description: "P95: {{ $value | humanize }}ms (umbral: 1000ms)"
          dashboard: "http://localhost:3302/d/k6-stress-test"
          action: "Optimizar aplicación o reducir carga"
      
      # ALERTA 35: Response time p95 crítico
      - alert: K6CriticalResponseTimeP95
        expr: k6_http_req_duration{quantile="0.95"} > 3000
        for: 1m
        labels:
          severity: critical
          service: k6-stress-testing
          component: performance
        annotations:
          summary: "⚠️ Response time p95 CRÍTICO en test K6"
          description: "P95: {{ $value | humanize }}ms (umbral crítico: 3000ms)"
          dashboard: "http://localhost:3302/d/k6-stress-test"
          action: "URGENTE: Sistema degradado, reducir carga"
      
      # ALERTA 36: Response time p99 muy alto
      - alert: K6HighResponseTimeP99
        expr: k6_http_req_duration{quantile="0.99"} > 5000
        for: 1m
        labels:
          severity: warning
          service: k6-stress-testing
          component: performance
        annotations:
          summary: "Response time p99 muy alto en test K6"
          description: "P99: {{ $value | humanize }}ms (umbral: 5000ms)"
          dashboard: "http://localhost:3302/d/k6-stress-test"
          action: "Revisar outliers y cuellos de botella"
      
      # ALERTA 37: Checks fallando en K6
      - alert: K6FailedChecks
        expr: k6_checks{result="fail"} > 0
        for: 1m
        labels:
          severity: warning
          service: k6-stress-testing
          component: validation
        annotations:
          summary: "Checks fallando en test K6"
          description: "{{ $value }} checks han fallado"
          dashboard: "http://localhost:3302/d/k6-stress-test"
          action: "Revisar validaciones del test y respuestas"
      
      # ALERTA 38: Alta tasa de requests
      - alert: K6HighRequestRate
        expr: rate(k6_http_reqs[1m]) > 1000
        for: 2m
        labels:
          severity: info
          service: k6-stress-testing
          component: load
        annotations:
          summary: "Alta tasa de requests en test K6"
          description: "{{ $value | humanize }} requests/s (info: > 1000)"
          dashboard: "http://localhost:3302/d/k6-stress-test"
          action: "Informativo: Test ejecutándose con alta carga"
      
      # ALERTA 39: Muchos VUs activos
      - alert: K6HighVirtualUsers
        expr: k6_vus > 100
        for: 1m
        labels:
          severity: info
          service: k6-stress-testing
          component: load
        annotations:
          summary: "Muchos usuarios virtuales en test K6"
          description: "{{ $value }} VUs activos (info: > 100)"
          dashboard: "http://localhost:3302/d/k6-stress-test"
          action: "Informativo: Test de alta carga ejecutándose"

  - name: k6_availability_alerts
    interval: 30s
    rules:
      # ALERTA 40: K6 Pushgateway no recibe métricas
      - alert: K6MetricsNotReceived
        expr: time() - push_time_seconds{job="k6-stress-test"} > 300
        for: 1m
        labels:
          severity: warning
          service: k6-stress-testing
          component: metrics
        annotations:
          summary: "K6 no está enviando métricas"
          description: "No se han recibido métricas de K6 en 5 minutos"
          dashboard: "http://localhost:9093"
          action: "Verificar que K6 está ejecutándose y enviando métricas"
