# ALERTAS DE NETDATA
# Monitorea m칠tricas avanzadas del sistema y servicios
# Reemplaza alertas de RabbitMQ con monitoreo m치s completo

groups:
  - name: netdata_system_health
    interval: 30s
    rules:
      # ALERTA 21: Netdata Down
      - alert: NetdataDown
        expr: up{job="netdata"} == 0
        for: 1m
        labels:
          severity: critical
          service: netdata
          component: monitoring
        annotations:
          summary: "游댮 Netdata CA칈DO - Sin m칠tricas de sistema en tiempo real"
          description: "춰CR칈TICO! Netdata no responde. Sin Netdata, perdemos visibilidad en tiempo real de: CPU por core, RAM detallada, I/O de disco, red por interfaz, procesos individuales, logs del sistema. Es nuestra herramienta principal de diagn칩stico en tiempo real."
          dashboard: "http://localhost:19999"
          action: "游뚿 URGENTE: 1) Ver contenedor: 'docker ps | grep netdata'. 2) Ver logs: 'docker logs ensurance-netdata-full --tail 50'. 3) Reiniciar: 'docker restart ensurance-netdata-full'. 4) Verificar acceso: 'curl http://localhost:19999/api/v1/info'. 5) Revisar permisos de /proc y /sys."

      # ALERTA 22: Temperatura CPU alta
      - alert: HighCPUTemperature
        expr: netdata_sensors_temperature_celsius_average > 80
        for: 5m
        labels:
          severity: warning
          service: system
          component: hardware
        annotations:
          summary: "丘멆잺 Temperatura CPU alta - Riesgo de throttling"
          description: "La temperatura de la CPU est치 en {{ $value }}춿C (umbral: 80춿C). Temperaturas altas causan: throttling de CPU (reducci칩n de frecuencia), degradaci칩n de rendimiento, riesgo de da침o de hardware, reinicios inesperados. El servidor puede estar en ambiente caliente o con ventilaci칩n bloqueada."
          dashboard: "http://localhost:19999/#menu_sensors"
          action: "游댌 Verificar: 1) Ver temperatura: 'sensors' o revisar Netdata. 2) Limpiar ventiladores. 3) Verificar flujo de aire. 4) Reducir carga si es posible. 5) Considerar mejor enfriamiento o migrar carga."

      # ALERTA 23: Procesos en estado Zombie
      - alert: ZombieProcesses
        expr: netdata_system_processes_state_zombies_processes > 10
        for: 10m
        labels:
          severity: warning
          service: system
          component: processes
        annotations:
          summary: "丘멆잺 Procesos Zombie detectados - Posible fuga de recursos"
          description: "Hay {{ $value }} procesos zombie en el sistema (umbral: 10). Los zombies son procesos terminados que no fueron limpiados por su proceso padre. Aunque no consumen CPU/RAM, indican bugs en aplicaciones. Demasiados zombies pueden agotar PIDs disponibles y prevenir creaci칩n de nuevos procesos."
          dashboard: "http://localhost:19999/#menu_system_submenu_processes"
          action: "游댌 Investigar: 1) Ver zombies: 'ps aux | grep defunct'. 2) Identificar proceso padre: 'ps -eo pid,ppid,stat,cmd | grep Z'. 3) Reiniciar proceso padre problem치tico. 4) Si es recurrente, reportar bug a desarrollo. 5) Como 칰ltimo recurso: reiniciar sistema."

      # ALERTA 24: Demasiados procesos corriendo
      - alert: TooManyProcesses
        expr: netdata_system_processes_running_processes > 500
        for: 5m
        labels:
          severity: warning
          service: system
          component: processes
        annotations:
          summary: "丘멆잺 Cantidad excesiva de procesos - Posible fork bomb o leak"
          description: "El sistema tiene {{ $value }} procesos corriendo (umbral: 500). Esto puede indicar: fork bomb (ataque o bug), memory leak en aplicaci칩n que crea threads, mal manejo de workers/pools. Demasiados procesos degradan el scheduler y consumen recursos."
          dashboard: "http://localhost:19999/#menu_system_submenu_processes"
          action: "游뚿 Investigar urgente: 1) Ver procesos: 'ps aux --sort=-%cpu | head -20'. 2) Contar por usuario: 'ps hax -o user | sort | uniq -c | sort -rn'. 3) Si es fork bomb, matar proceso padre. 4) Limitar con ulimit si es necesario. 5) Revisar aplicaciones que crean m칰ltiples procesos."

      # ALERTA 25: Swap en uso (sin RAM disponible)
      - alert: SwapUsage
        expr: (netdata_mem_swap_MiB_average / netdata_system_ram_MiB_average) * 100 > 25
        for: 10m
        labels:
          severity: warning
          service: system
          component: memory
        annotations:
          summary: "丘멆잺 Sistema usando Swap - RAM insuficiente, rendimiento degradado"
          description: "El sistema est치 usando {{ $value }}% de swap (umbral: 25%). El swap es disco usado como memoria - extremadamente lento. Cuando se usa swap, el sistema se vuelve lento porque cada acceso a memoria es en realidad I/O de disco. Indica que la RAM f칤sica se agot칩 completamente."
          dashboard: "http://localhost:19999/#menu_mem"
          action: "游댌 Reducir uso de RAM: 1) Ver swap: 'free -h' y 'swapon -s'. 2) Identificar procesos usando swap: 'for file in /proc/*/status; do awk '/VmSwap|Name/{printf $2 \" \" $3}END{ print \"\"}' $file; done | sort -k 2 -n -r | head'. 3) Reiniciar procesos pesados. 4) Agregar m치s RAM. 5) Deshabilitar swap si no es necesario."

      # ALERTA 26: I/O de disco muy alto
      - alert: HighDiskIO
        expr: rate(netdata_disk_io_time_percentage_average[5m]) > 80
        for: 5m
        labels:
          severity: warning
          service: system
          component: disk
        annotations:
          summary: "丘멆잺 I/O de disco saturado - Cuello de botella de rendimiento"
          description: "El disco {{ $labels.family }} est치 al {{ $value }}% de utilizaci칩n I/O (umbral: 80%). El disco est치 saturado procesando lecturas/escrituras. Esto causa: lentitud en todas las aplicaciones, queries de DB lentas, writes bloqueados, load average alto. El disco no puede procesar m치s operaciones simult치neas."
          dashboard: "http://localhost:19999/#menu_disk"
          action: "游댌 Optimizar I/O: 1) Ver qu칠 escribe: 'iotop -o'. 2) Ver procesos con I/O: 'pidstat -d 1'. 3) Identificar: logs excesivos, DB sin 칤ndices, backups en progreso. 4) Usar cach칠 si es posible. 5) Migrar a SSD o disco m치s r치pido. 6) Mover cargas pesadas a otros horarios."

      # ALERTA 27: Alta fragmentaci칩n de memoria
      - alert: MemoryFragmentation
        expr: netdata_mem_fragmentation_index_ratio > 0.7
        for: 15m
        labels:
          severity: warning
          service: system
          component: memory
        annotations:
          summary: "丘멆잺 Memoria fragmentada - Asignaciones grandes pueden fallar"
          description: "La memoria tiene un 칤ndice de fragmentaci칩n de {{ $value }} (umbral: 0.7, donde 1.0 es completamente fragmentado). Alta fragmentaci칩n significa que aunque haya RAM libre, est치 en pedazos peque침os. Aplicaciones que requieren bloques grandes contiguos pueden fallar con 'out of memory' aunque el sistema reporte RAM disponible."
          dashboard: "http://localhost:19999/#menu_mem"
          action: "游댌 Desfragmentar: 1) Ver fragmentaci칩n: 'cat /proc/buddyinfo'. 2) Compactar: 'echo 1 > /proc/sys/vm/compact_memory'. 3) Liberar caches: 'sync; echo 3 > /proc/sys/vm/drop_caches'. 4) Reiniciar servicios si es cr칤tico. 5) Considerar reinicio del sistema en mantenimiento."

      # ALERTA 28: Errores de lectura en disco
      - alert: DiskReadErrors
        expr: increase(netdata_disk_io_errors_read_errors[10m]) > 5
        for: 5m
        labels:
          severity: critical
          service: system
          component: disk
        annotations:
          summary: "游댮 Errores de lectura en disco {{ $labels.family }} - Fallo de hardware inminente"
          description: "춰CR칈TICO! El disco {{ $labels.family }} ha tenido {{ $value }} errores de lectura en los 칰ltimos 10 minutos. Errores de lectura indican: sectores da침ados, fallo inminente del disco, controladora fallando, cables sueltos. ALTO RIESGO DE P칄RDIDA DE DATOS. El disco puede fallar completamente en cualquier momento."
          dashboard: "http://localhost:19999/#menu_disk"
          action: "游뚿 ACCI칍N INMEDIATA: 1) Ver SMART: 'smartctl -a /dev/sda'. 2) BACKUP URGENTE de datos cr칤ticos. 3) Ver dmesg: 'dmesg | grep -i error'. 4) Revisar conexiones f칤sicas. 5) REEMPLAZAR DISCO urgentemente. 6) Migrar servicios a otro servidor si es posible."

      # ALERTA 29: Conexiones de red sospechosas
      - alert: SuspiciousNetworkConnections
        expr: netdata_ipv4_tcp_connections_active_connections > 1000
        for: 5m
        labels:
          severity: warning
          service: system
          component: network
        annotations:
          summary: "丘멆잺 N칰mero inusual de conexiones TCP - Posible ataque o fuga"
          description: "El sistema tiene {{ $value }} conexiones TCP activas (umbral: 1000). Esto puede indicar: ataque DDoS, port scanning, botnet, fuga de conexiones en aplicaci칩n, muchos usuarios leg칤timos. Revisar para determinar si es tr치fico leg칤timo o malicioso."
          dashboard: "http://localhost:19999/#menu_ipv4"
          action: "游댌 Investigar conexiones: 1) Contar por IP: 'netstat -tn | awk '{print $5}' | cut -d: -f1 | sort | uniq -c | sort -rn | head -20'. 2) Ver estados: 'netstat -tan | awk '{print $6}' | sort | uniq -c'. 3) Bloquear IPs sospechosas con iptables. 4) Implementar rate limiting. 5) Contactar proveedor si es ataque DDoS."

      # ALERTA 30: Reinicios frecuentes de servicio
      - alert: FrequentServiceRestarts
        expr: increase(netdata_systemd_service_unit_failed_state_activations_activations[30m]) > 5
        for: 5m
        labels:
          severity: warning
          service: systemd
          component: service-management
        annotations:
          summary: "丘멆잺 Servicio {{ $labels.service }} reiniciando frecuentemente - Inestabilidad"
          description: "El servicio {{ $labels.service }} ha fallado y reiniciado {{ $value }} veces en 30 minutos. Reinicios frecuentes indican: crashes constantes, bug en el c칩digo, recursos insuficientes, configuraci칩n incorrecta, dependencias faltantes. El servicio est치 inestable."
          dashboard: "http://localhost:19999/#menu_systemd"
          action: "游댌 Estabilizar servicio: 1) Ver logs: 'journalctl -u {{ $labels.service }} -n 100'. 2) Ver status: 'systemctl status {{ $labels.service }}'. 3) Revisar recursos. 4) Verificar configuraci칩n. 5) Deshabilitar auto-restart temporalmente para investigar. 6) Reportar a desarrollo si es bug."

      # ALERTA 31: Logs del sistema creciendo r치pidamente
      - alert: RapidLogGrowth
        expr: rate(netdata_disk_space_MiB_average{family="/var/log"}[5m]) * 3600 > 1000
        for: 10m
        labels:
          severity: warning
          service: system
          component: logs
        annotations:
          summary: "丘멆잺 Logs creciendo r치pidamente - Riesgo de llenar disco"
          description: "Los logs en /var/log est치n creciendo a {{ $value }} MB/hora. Crecimiento r치pido indica: errores en loop, logging excesivo (debug level), ataque generando logs, aplicaci칩n mal configurada. Si contin칰a, puede llenar el disco y causar fallo del sistema."
          dashboard: "http://localhost:19999/#menu_disk_space"
          action: "游댌 Controlar logs: 1) Ver archivos grandes: 'du -sh /var/log/* | sort -rh | head -10'. 2) Ver logs activos: 'lsof | grep /var/log'. 3) Rotar logs: 'logrotate -f /etc/logrotate.conf'. 4) Reducir nivel de logging. 5) Implementar log rotation agresivo. 6) Investigar qu칠 genera tantos logs."

      # ALERTA 32: Latencia de red alta
      - alert: HighNetworkLatency
        expr: netdata_ping_latency_ms_average > 100
        for: 5m
        labels:
          severity: warning
          service: network
          component: connectivity
        annotations:
          summary: "丘멆잺 Latencia de red alta hacia {{ $labels.dimension }} - Conectividad degradada"
          description: "La latencia de ping hacia {{ $labels.dimension }} es {{ $value }}ms (umbral: 100ms). Alta latencia causa: timeouts en APIs, lentitud en cargas de p치gina, operaciones de BD remotas lentas, experiencia de usuario degradada. Puede indicar: congesti칩n de red, ISP con problemas, saturaci칩n de ancho de banda."
          dashboard: "http://localhost:19999/#menu_ping"
          action: "游댌 Diagnosticar red: 1) Ping manual: 'ping -c 10 {{ $labels.dimension }}'. 2) Traceroute: 'traceroute {{ $labels.dimension }}'. 3) Ver uso de ancho de banda: 'iftop'. 4) Verificar QoS. 5) Contactar ISP si persiste. 6) Considerar CDN o cach칠 si es servicio externo."
