# ALERTAS DE SISTEMA - Node Exporter
# Monitorea m칠tricas del sistema: CPU, Memoria, Disco, Red

groups:
  - name: system_ram_alerts
    interval: 30s
    rules:
      # ALERTA 0: RAM Usage > 60% (se ejecuta primero)
      - alert: HighRAMUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 60
        for: 1m
        labels:
          severity: warning
          service: system
          component: ram
        annotations:
          summary: "丘멆잺 Uso de RAM elevado - Monitoreo preventivo"
          description: "El servidor {{ $labels.instance }} tiene un uso de RAM de {{ $value | humanize }}% (umbral de alerta: 60%). Esta es una advertencia temprana para evitar saturaci칩n de memoria. La memoria disponible se est치 reduciendo y es momento de revisar qu칠 aplicaciones est치n consumiendo recursos."
          dashboard: "http://localhost:19999"
          action: "游댌 Ejecutar 'ps aux --sort=-%mem | head -20' para ver procesos con m치s memoria. Revisar logs de aplicaciones y considerar liberar cache si es necesario. Monitorear tendencia de uso."

  - name: system_cpu_alerts
    interval: 30s
    rules:
      # ALERTA 1: CPU Usage > 70%
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 70
        for: 2m
        labels:
          severity: warning
          service: system
          component: cpu
        annotations:
          summary: "丘멆잺 CPU elevada - Rendimiento puede verse afectado"
          description: "El servidor {{ $labels.instance }} est치 usando {{ $value | humanize }}% de CPU (umbral: 70%). El procesamiento est치 por encima de lo normal. Si contin칰a subiendo, podr칤a afectar el rendimiento de las aplicaciones y tiempos de respuesta."
          dashboard: "http://localhost:19999"
          action: "游댌 Identificar procesos: 'top -o %CPU' o 'htop'. Revisar logs de aplicaciones. Si es Ensurance/Pharmacy backend, considerar escalar horizontalmente o optimizar consultas."
      
      # ALERTA 2: CPU Usage > 90% - CR칈TICO
      - alert: CriticalCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
        for: 1m
        labels:
          severity: critical
          service: system
          component: cpu
        annotations:
          summary: "游댮 CPU CR칈TICO - Sistema saturado - Acci칩n inmediata"
          description: "춰ALERTA CR칈TICA! El servidor {{ $labels.instance }} est치 usando {{ $value | humanize }}% de CPU (umbral cr칤tico: 90%). El sistema est치 saturado y las aplicaciones est치n experimentando degradaci칩n severa de rendimiento. Los usuarios pueden estar experimentando lentitud o timeouts."
          dashboard: "http://localhost:19999"
          action: "游뚿 URGENTE: 1) Ver procesos: 'ps aux --sort=-%cpu | head'. 2) Matar procesos si es necesario: 'kill -9 PID'. 3) Reiniciar servicios Docker si aplica. 4) Escalar recursos o agregar CPU. 5) Revisar si hay bucles infinitos o consultas pesadas."

  - name: system_memory_alerts
    interval: 30s
    rules:
      # ALERTA 3: Memory Usage > 80%
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 80
        for: 2m
        labels:
          severity: warning
          service: system
          component: memory
        annotations:
          summary: "丘멆잺 Memoria alta - Riesgo de saturaci칩n"
          description: "El servidor {{ $labels.instance }} est치 usando {{ $value | humanize }}% de memoria RAM (umbral: 80%). La memoria disponible es limitada. Si alcanza 95%, el kernel puede activar el OOM killer y matar procesos autom치ticamente."
          dashboard: "http://localhost:19999"
          action: "游댌 Investigar: 'free -h' y 'ps aux --sort=-%mem | head -15'. Revisar si hay memory leaks en Node.js/Java. Considerar reiniciar servicios o liberar cache: 'sync; echo 3 > /proc/sys/vm/drop_caches'."
      
      # ALERTA 4: Memory Usage > 95% - CR칈TICO
      - alert: CriticalMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 95
        for: 1m
        labels:
          severity: critical
          service: system
          component: memory
        annotations:
          summary: "游댮 MEMORIA CR칈TICA - OOM killer puede activarse"
          description: "춰EMERGENCIA! El servidor {{ $labels.instance }} est치 usando {{ $value | humanize }}% de memoria (umbral cr칤tico: 95%). El sistema est치 al borde del colapso. El kernel Linux puede activar el OOM (Out Of Memory) killer en cualquier momento, lo cual matar치 procesos para liberar memoria, potencialmente incluyendo tus aplicaciones cr칤ticas."
          dashboard: "http://localhost:19999"
          action: "游뚿 ACCI칍N INMEDIATA: 1) Reiniciar servicios no cr칤ticos. 2) 'docker restart [contenedores]'. 3) Liberar cache: 'sync; echo 3 > /proc/sys/vm/drop_caches'. 4) Revisar 'dmesg | grep -i oom' para ver si ya hay kills. 5) Escalar RAM urgentemente."

  - name: system_disk_alerts
    interval: 30s
    rules:
      # ALERTA 5: Disk Usage > 75%
      - alert: HighDiskUsage
        expr: (1 - (node_filesystem_avail_bytes{fstype!~"tmpfs|fuse.lxcfs|squashfs|vfat"} / node_filesystem_size_bytes)) * 100 > 75
        for: 5m
        labels:
          severity: warning
          service: system
          component: disk
        annotations:
          summary: "丘멆잺 Espacio en disco limitado - Planificar limpieza"
          description: "El disco {{ $labels.mountpoint }} en {{ $labels.instance }} est치 usando {{ $value | humanize }}% de su capacidad (umbral: 75%). El espacio disponible se est치 agotando. Si alcanza 90%, las aplicaciones pueden fallar al intentar escribir logs, bases de datos o archivos temporales."
          dashboard: "http://localhost:19999"
          action: "游댌 Analizar uso: 'df -h' y 'du -sh /* | sort -rh | head -10'. Limpiar: logs antiguos, Docker: 'docker system prune -a', cach칠s, archivos temp en /tmp. Revisar rotaci칩n de logs."
      
      # ALERTA 6: Disk Usage > 90% - CR칈TICO
      - alert: CriticalDiskUsage
        expr: (1 - (node_filesystem_avail_bytes{fstype!~"tmpfs|fuse.lxcfs|squashfs|vfat"} / node_filesystem_size_bytes)) * 100 > 90
        for: 2m
        labels:
          severity: critical
          service: system
          component: disk
        annotations:
          summary: "游댮 DISCO CR칈TICO - Fallo inminente de aplicaciones"
          description: "춰CR칈TICO! El disco {{ $labels.mountpoint }} en {{ $labels.instance }} est치 al {{ $value | humanize }}% (umbral cr칤tico: 90%). Las aplicaciones pueden comenzar a fallar. Bases de datos no podr치n escribir, logs se detendr치n, y servicios pueden crashear por falta de espacio."
          dashboard: "http://localhost:19999"
          action: "游뚿 URGENTE: 1) Liberar espacio AHORA: 'docker system prune -af --volumes'. 2) Eliminar logs: 'find /var/log -name *.log -mtime +7 -delete'. 3) Ver archivos grandes: 'find / -type f -size +100M 2>/dev/null'. 4) Expandir volumen o agregar disco."
      
      # ALERTA 7: Disk casi lleno (< 5GB libre)
      - alert: DiskAlmostFull
        expr: node_filesystem_avail_bytes{fstype!~"tmpfs|fuse.lxcfs|squashfs|vfat"} / 1024 / 1024 / 1024 < 5
        for: 5m
        labels:
          severity: warning
          service: system
          component: disk
        annotations:
          summary: "丘멆잺 Disco con espacio cr칤tico - Menos de 5GB disponibles"
          description: "El disco {{ $labels.mountpoint }} en {{ $labels.instance }} tiene solo {{ $value | humanize }}GB libres (menos de 5GB). Aunque el porcentaje no sea alto, el espacio absoluto es cr칤tico. Sistemas con poca RAM pueden necesitar swap, bases de datos requieren espacio para operaciones, y logs pueden crecer r치pidamente."
          dashboard: "http://localhost:19999"
          action: "游댌 Liberar espacio: 1) 'docker system prune -f'. 2) Limpiar logs: 'journalctl --vacuum-time=3d'. 3) Revisar /tmp y /var/tmp. 4) Comprimir o mover archivos grandes a otro volumen."

  - name: system_network_alerts
    interval: 30s
    rules:
      # ALERTA 8: Alto tr치fico de red entrante
      - alert: HighNetworkReceive
        expr: rate(node_network_receive_bytes_total[5m]) / 1024 / 1024 > 100
        for: 5m
        labels:
          severity: warning
          service: system
          component: network
        annotations:
          summary: "丘멆잺 Tr치fico de red entrante anormalmente alto"
          description: "El servidor {{ $labels.instance }} est치 recibiendo {{ $value | humanize }}MB/s de tr치fico (umbral: 100MB/s). Esto puede indicar: tr치fico leg칤timo alto (muchos usuarios), ataque DDoS, scraping masivo, o transferencia de datos grande. Monitorear para determinar si es normal o malicioso."
          dashboard: "http://localhost:19999"
          action: "游댌 Investigar: 1) Ver conexiones: 'netstat -tnp | grep ESTABLISHED | wc -l'. 2) IPs con m치s conexiones: 'netstat -tnp | awk '{print $5}' | cut -d: -f1 | sort | uniq -c | sort -nr | head'. 3) Revisar logs de Nginx/Apache. 4) Considerar rate limiting o firewall."
      
      # ALERTA 9: Alto tr치fico de red saliente
      - alert: HighNetworkTransmit
        expr: rate(node_network_transmit_bytes_total[5m]) / 1024 / 1024 > 100
        for: 5m
        labels:
          severity: warning
          service: system
          component: network
        annotations:
          summary: "丘멆잺 Tr치fico de red saliente anormalmente alto"
          description: "El servidor {{ $labels.instance }} est치 enviando {{ $value | humanize }}MB/s de tr치fico (umbral: 100MB/s). Puede indicar: backups leg칤timos, sincronizaci칩n de datos, respuestas a muchos usuarios, o en el peor caso, exfiltraci칩n de datos o servidor comprometido enviando spam/ataques."
          dashboard: "http://localhost:19999"
          action: "游댌 Investigar: 1) Procesos con red: 'iftop' o 'nethogs'. 2) Conexiones establecidas: 'netstat -tnp'. 3) Revisar si es backup programado o sincronizaci칩n normal. 4) Revisar logs de seguridad. 5) Si es sospechoso, aislar servidor."

  - name: system_availability_alerts
    interval: 30s
    rules:
      # ALERTA 10: Node Exporter Down
      - alert: NodeExporterDown
        expr: up{job="node-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          service: system
          component: node-exporter
        annotations:
          summary: "游댮 Node Exporter ca칤do - Sin m칠tricas del sistema"
          description: "춰CR칈TICO! El Node Exporter en {{ $labels.instance }} no responde. Sin este servicio, Prometheus no puede recolectar m칠tricas del sistema (CPU, RAM, disco, red). Est치s volando a ciegas - no hay visibilidad del estado del servidor. Otras alertas de sistema no funcionar치n hasta que se recupere."
          dashboard: "http://localhost:19999"
          action: "游뚿 URGENTE: 1) Verificar contenedor: 'docker ps | grep node-exporter'. 2) Ver logs: 'docker logs ensurance-node-exporter'. 3) Reiniciar: 'docker restart ensurance-node-exporter'. 4) Si persiste, revisar configuraci칩n en docker-compose.full.yml."
      
      # ALERTA 11: Sistema con alta carga (Load Average)
      - alert: HighSystemLoad
        expr: node_load5 / count(node_cpu_seconds_total{mode="idle"}) without(cpu, mode) > 2
        for: 5m
        labels:
          severity: warning
          service: system
          component: load
        annotations:
          summary: "丘멆잺 Carga del sistema elevada - Sistema bajo presi칩n"
          description: "El load average (5 min) en {{ $labels.instance }} es {{ $value | humanize }}, m치s del doble de CPUs disponibles. Esto significa que hay m치s procesos esperando ejecutarse que CPUs disponibles. El sistema est치 sobrecargado y los procesos est치n en cola, causando lentitud generalizada."
          dashboard: "http://localhost:19999"
          action: "游댌 Diagnosticar: 1) Ver load: 'uptime'. 2) Procesos: 'top' o 'htop'. 3) I/O wait: 'iostat -x 1'. 4) Si load es por I/O, revisar disco. 5) Si es por CPU, identificar procesos pesados. 6) Considerar escalar o optimizar aplicaciones."
