services:
  k6:
    build:
      context: ../stress/k6
      dockerfile: Dockerfile.k6-prometheus
    image: ensurance-k6-prometheus:latest
    container_name: ensurance-k6
    user: "0:0"
    command:
      - "run"
      - "--out"
      - "json=/results/k6-results.json"
      - "--out"
      - "experimental-prometheus-rw"
      - "--out"
      - "web-dashboard=export=/results/k6-report.html"
      - "--summary-export=/results/summary.json"
      - "/scripts/${TEST_SCRIPT:-sample-script.js}"
    environment:
      K6_PROMETHEUS_RW_SERVER_URL: "http://prometheus:9090/api/v1/write"
      K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM: "false"
      K6_PROMETHEUS_RW_PUSH_INTERVAL: "5s"
      K6_PROMETHEUS_RW_TREND_STATS: "p(95),p(99),min,max,avg,med"
      K6_PROMETHEUS_RW_INSECURE_SKIP_TLS_VERIFY: "true"
      BACKV4_URL: "${BACKV4_URL:-http://host.docker.internal:3002}"
      BACKV5_URL: "${BACKV5_URL:-http://host.docker.internal:3003}"
    volumes:
      - ../stress/k6/scripts:/scripts:ro
      - k6_results:/results
    ports:
      - "5665:5665"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "no"
    networks:
      - stress-test-network
      - monitoring-network

  jmeter:
    image: alpine/jmeter:5.6.3
    container_name: ensurance-jmeter
    entrypoint: ["/custom-entrypoint.sh"]
    command:
      - "-n"
      - "-t"
      - "/testplans/${JMETER_PLAN:-sample-plan.jmx}"
      - "-l"
      - "/results/results.jtl"
      - "-e"
      - "-o"
      - "/results/report"
      - "-JBACKV4_URL=${BACKV4_URL:-http://host.docker.internal:3002}"
      - "-JBACKV5_URL=${BACKV5_URL:-http://host.docker.internal:3003}"
      - "-JUSERS=${USERS:-50}"
      - "-JRAMP_TIME=${RAMP_TIME:-30}"
      - "-JDURATION=${DURATION:-300}"
    volumes:
      - ../stress/jmeter/test-plans:/testplans:ro
      - jmeter_results:/results
      - ./jmeter-entrypoint.sh:/custom-entrypoint.sh:ro
    ports:
      - "8085:8085"
    restart: "no"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - stress-test-network

  k6-report:
    image: python:3.9-alpine
    container_name: ensurance-k6-report
    working_dir: /results
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        # Create index.html with links to all reports
        cat > /results/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <meta http-equiv="refresh" content="0; url=/k6-report.html">
          <title>K6 Dashboard</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
            .container { background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
            h1 { color: #7d64ff; }
            a { color: #7d64ff; text-decoration: none; font-weight: bold; }
            a:hover { text-decoration: underline; }
            .links { margin-top: 20px; }
            .links div { margin: 10px 0; }
          </style>
        </head>
        <body>
          <div class="container">
            <h1>📊 K6 Test Reports</h1>
            <p>Redirecting to K6 Dashboard...</p>
            <div class="links">
              <div>🎨 <a href="/k6-report.html">Interactive Dashboard (Recommended)</a></div>
              <div>📄 <a href="/k6-results.json">Raw JSON Results</a></div>
              <div>📊 <a href="/summary.json">Summary JSON</a></div>
            </div>
          </div>
        </body>
        </html>
        EOF
        python -m http.server 5666
    volumes:
      - k6_results:/results
    ports:
      - "5666:5666"
    restart: unless-stopped
    networks:
      - stress-test-network
    labels:
      - "com.ensurance.service=k6-report"
      - "com.ensurance.description=K6 HTML Dashboard Server"

  jmeter-report:
    image: python:3.9-alpine
    container_name: ensurance-jmeter-report
    working_dir: /results/report
    command: python -m http.server 8085
    volumes:
      - jmeter_results:/results
    ports:
      - "8085:8085"
    restart: unless-stopped
    networks:
      - stress-test-network
    labels:
      - "com.ensurance.service=jmeter-report"
      - "com.ensurance.description=JMeter HTML Report Server"

networks:
  stress-test-network:
    driver: bridge
  monitoring-network:
    external: true
    name: scripts_monitoring-network

volumes:
  k6_results:
  jmeter_results:
