services:
  k6:
    build:
      context: ../stress/k6
      dockerfile: Dockerfile.k6-prometheus
    image: ensurance-k6-prometheus:latest
    container_name: ensurance-k6
    user: "0:0"
    command:
      - "run"
      - "--out"
      - "json=/results/k6-results.json"
      - "--out"
      - "experimental-prometheus-rw"
      - "--summary-export=/results/summary.json"
      - "/scripts/${TEST_SCRIPT:-sample-script.js}"
    environment:
      K6_WEB_DASHBOARD_EXPORT: "/results/k6-dashboard"
      K6_PROMETHEUS_RW_SERVER_URL: "http://prometheus:9090/api/v1/write"
      K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM: "false"
      K6_PROMETHEUS_RW_PUSH_INTERVAL: "5s"
      K6_PROMETHEUS_RW_TREND_STATS: "p(95),p(99),min,max,avg,med"
      K6_PROMETHEUS_RW_INSECURE_SKIP_TLS_VERIFY: "true"
      BACKV4_URL: "${BACKV4_URL:-http://host.docker.internal:3002}"
      BACKV5_URL: "${BACKV5_URL:-http://host.docker.internal:3003}"
    volumes:
      - ../stress/k6/scripts:/scripts:ro
      - k6_results:/results
    ports:
      - "5665:5665"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "no"
    networks:
      - stress-test-network
      - monitoring-network

  jmeter:
    image: alpine/jmeter:5.6.3
    container_name: ensurance-jmeter
    entrypoint: ["/custom-entrypoint.sh"]
    command:
      - "-n"
      - "-t"
      - "/testplans/${JMETER_PLAN:-sample-plan.jmx}"
      - "-l"
      - "/results/results.jtl"
      - "-e"
      - "-o"
      - "/results/report"
      - "-JBACKV4_URL=${BACKV4_URL:-http://host.docker.internal:3002}"
      - "-JBACKV5_URL=${BACKV5_URL:-http://host.docker.internal:3003}"
      - "-JUSERS=${USERS:-50}"
      - "-JRAMP_TIME=${RAMP_TIME:-30}"
      - "-JDURATION=${DURATION:-300}"
    volumes:
      - ../stress/jmeter/test-plans:/testplans:ro
      - jmeter_results:/results
      - ./jmeter-entrypoint.sh:/custom-entrypoint.sh:ro
    ports:
      - "8085:8085"
    restart: "no"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - stress-test-network

  k6-report:
    image: python:3.9-alpine
    container_name: ensurance-k6-report
    working_dir: /results
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        # Rename k6-dashboard to .html extension if it exists
        if [ -f /results/k6-dashboard ]; then
          cp /results/k6-dashboard /results/k6-dashboard.html
        fi
        
        # Create index.html with redirect
        cat > /results/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <meta http-equiv="refresh" content="0; url=/k6-dashboard.html">
          <title>K6 Dashboard</title>
        </head>
        <body>
          <p>Redirecting to K6 Dashboard...</p>
          <p>If not redirected, <a href="/k6-dashboard.html">click here</a></p>
        </body>
        </html>
        EOF
        python -m http.server 5666
    volumes:
      - k6_results:/results
    ports:
      - "5666:5666"
    restart: unless-stopped
    networks:
      - stress-test-network
    labels:
      - "com.ensurance.service=k6-report"
      - "com.ensurance.description=K6 HTML Dashboard Server"

  jmeter-report:
    image: python:3.9-alpine
    container_name: ensurance-jmeter-report
    working_dir: /results/report
    command: python -m http.server 8085
    volumes:
      - jmeter_results:/results
    ports:
      - "8085:8085"
    restart: unless-stopped
    networks:
      - stress-test-network
    labels:
      - "com.ensurance.service=jmeter-report"
      - "com.ensurance.description=JMeter HTML Report Server"

networks:
  stress-test-network:
    driver: bridge
  monitoring-network:
    external: true
    name: scripts_monitoring-network

volumes:
  k6_results:
  jmeter_results:
